name: Purge Statically Cache

on:
  push:
    paths:
      - 'list.txt'
      - 'proxylist.txt' # Теперь GitHub следит за обоими файлами

jobs:
  purge:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Statically Purge
        run: |
          # Сбрасываем кэш для первого файла
          curl -X POST https://statically.io \
          -H "Content-Type: application/json" \
          -d '{"url": "https://statically.io"}'
          
          # Сбрасываем кэш для второго файла
          curl -X POST https://statically.io \
          -H "Content-Type: application/json" \
          -d '{"url": "https://statically.io"}'
